// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

// Prisma CLI (generate/typecheck) грузит этот файл даже когда `.env` не настроен.
// Для генерации клиентских типов подключение к БД не требуется, но `env('DATABASE_URL')` обязателен.
// Даем безопасный дефолт для локальной разработки; в реальном окружении переменная должна быть задана явно.
if (!process.env.DATABASE_URL) {
  process.env.DATABASE_URL = 'mongodb://localhost:27017/voice-assistant';
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    url: env('DATABASE_URL'),
  },
});
